#CLIENTE --> OBJETIVO: seguridad
server:  
  port: ${PORT:8881}

#Proyecto cliente que nececita matricularse
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8879/eureka/
      
#Configurar oauth2     
security:
  oauth2:
    client:
      client-id: pachis
      client-secret: secret
      authorized-grant-types: password,client_credentials,authorization_code,refresh_token
      scope: read,write      
      access-token-validity-seconds: 30
      
#Credenciales
spring:    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/sirabiProject
    username: postgres
    password: postgres123

logging:  
  file: /home/isaac/Documents/logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.web: 'WARN'
    org.renapo: 'WARN'
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} | [%thread] | %-5level | %logger{36} - %msg%n"
